### ISSUE TITLE
Creating Account Action from WasmMsg directly

### ISSUE THREAD

**Issue by Kayanski** [AbstractSDK/contracts#354]
Account Actions can be created directly from Cosmos Messages using : https://github.com/AbstractSDK/contracts/blob/main/packages/abstract-sdk/src/account_action.rs#L26
However  the  `cosmwasm_std::wasm_execute` function that is very nice to use returns a `WasmMsg` that is not directly convertiable to an `AccountAction`.

I propose we implement  `From<WasmMsg> for AccountAction` as well to simplify creating proxy messages

**Comment by Buckram123** [comment]
Or even `From<Into<CosmosMsg>>`
